const verifiedHospitals = [
  {
    name: "横浜市立市民病院",
    area: "横浜市神奈川区三ツ沢西町1-1",
    region: "横浜市",
    officialUrl: "https://yokohama-shiminhosp.jp/",
    recruitUrl: "https://yokohama-shiminhosp.jp/saiyo",
    image: "/assets/real-hospitals/yokohama-shimin-hospital.jpg",
    imageNote: "公式サイトの外観を参考にした独自生成画像",
    access: "横浜駅西口から市営バス・「市民病院」下車すぐ",
    type: "公立病院",
    designation: "災害拠点病院",
  },
  {
    name: "川崎市立川崎病院",
    area: "川崎市川崎区新川通12-1",
    region: "川崎市",
    officialUrl: "https://www.city.kawasaki.jp/kawasaki_hospital/index.html",
    recruitUrl: "https://www.hospital-nurse.city.kawasaki.jp/index.html",
    image: "/assets/real-hospitals/kawasaki-city-hospital.jpg",
    imageNote: "公式サイトの外観を参考にした独自生成画像",
    access: "JR川崎駅東口から徒歩約15分・直通バスあり",
    type: "公立病院",
    designation: "災害拠点病院",
  },
  {
    name: "湘南鎌倉総合病院",
    area: "鎌倉市岡本1370-1",
    region: "湘南エリア",
    officialUrl: "https://www.skgh.jp/",
    recruitUrl: "https://www.shonankamakura.or.jp/career/",
    image: "/assets/real-hospitals/shonan-kamakura-general-hospital.jpg",
    imageNote: "公式サイトの外観を参考にした独自生成画像",
    access: "大船駅西口から無料シャトルバスあり",
    type: "総合病院",
    designation: "災害拠点病院",
  },
  {
    name: "昭和医科大学藤が丘病院",
    area: "横浜市青葉区藤が丘1-30",
    region: "横浜市",
    officialUrl: "https://www.showa-u.ac.jp/SUHF/",
    type: "大学病院",
    designation: "災害拠点病院",
  },
  {
    name: "横浜労災病院",
    area: "横浜市港北区小机町3211",
    region: "横浜市",
    officialUrl: "https://yokohamah.johas.go.jp/",
    designation: "災害拠点病院",
  },
  {
    name: "昭和医科大学横浜市北部病院",
    area: "横浜市都筑区茅ケ崎中央35-1",
    region: "横浜市",
    officialUrl: "https://www.showa-u.ac.jp/SUHY/",
    type: "大学病院",
    designation: "災害拠点病院",
  },
  {
    name: "済生会横浜市東部病院",
    area: "横浜市鶴見区下末吉3-6-1",
    region: "横浜市",
    officialUrl: "https://www.tobu.saiseikai.or.jp/",
    designation: "災害拠点病院",
  },
  {
    name: "聖マリアンナ医科大学横浜市西部病院",
    area: "横浜市旭区矢指町1197-1",
    region: "横浜市",
    officialUrl: "https://seibu.marianna-u.ac.jp/",
    type: "大学病院",
    designation: "災害拠点病院",
  },
  {
    name: "けいゆう病院",
    area: "横浜市西区みなとみらい3-7-3",
    region: "横浜市",
    officialUrl: "https://www.keiyu-hospital.com/",
    designation: "災害拠点病院",
  },
  {
    name: "国立病院機構横浜医療センター",
    area: "横浜市戸塚区原宿3-60-2",
    region: "横浜市",
    officialUrl: "https://yokohama.hosp.go.jp/",
    designation: "災害拠点病院",
  },
  {
    name: "横浜市立大学附属市民総合医療センター",
    area: "横浜市南区浦舟町4-57",
    region: "横浜市",
    officialUrl: "https://www.yokohama-cu.ac.jp/urahp/",
    type: "大学病院",
    designation: "災害拠点病院",
  },
  {
    name: "済生会横浜市南部病院",
    area: "横浜市港南区港南台3-2-10",
    region: "横浜市",
    officialUrl: "https://www.nanbu.saiseikai.or.jp/",
    designation: "災害拠点病院",
  },
  {
    name: "横浜市立大学附属病院",
    area: "横浜市金沢区福浦3-9",
    region: "横浜市",
    officialUrl: "https://www.yokohama-cu.ac.jp/fukuhp/",
    type: "大学病院",
    designation: "災害拠点病院",
  },
  {
    name: "横浜南共済病院",
    area: "横浜市金沢区六浦東1-21-1",
    region: "横浜市",
    officialUrl: "https://minamikyousai.kkr.or.jp/",
    designation: "災害拠点病院",
  },
  {
    name: "横浜市立みなと赤十字病院",
    area: "横浜市中区新山下3-12-1",
    region: "横浜市",
    officialUrl: "https://www.yokohama.jrc.or.jp/",
    type: "公立病院",
    designation: "災害拠点病院",
  },
  {
    name: "聖マリアンナ医科大学病院",
    area: "川崎市宮前区菅生2-16-1",
    region: "川崎市",
    officialUrl: "https://www.marianna-u.ac.jp/hospital/",
    type: "大学病院",
    designation: "災害拠点病院",
  },
  {
    name: "帝京大学医学部附属溝口病院",
    area: "川崎市高津区二子5-1-1",
    region: "川崎市",
    officialUrl: "https://www.teikyo-mizonokuchi.jp/",
    type: "大学病院",
    designation: "災害拠点病院",
  },
  {
    name: "川崎市立多摩病院",
    area: "川崎市多摩区宿河原1-30-37",
    region: "川崎市",
    officialUrl: "https://tama.marianna-u.ac.jp/",
    type: "公立病院",
    designation: "災害拠点病院",
  },
  {
    name: "関東労災病院",
    area: "川崎市中原区木月住吉町1-1",
    region: "川崎市",
    officialUrl: "https://www.kantoh.johas.go.jp/",
    designation: "災害拠点病院",
  },
  {
    name: "日本医科大学武蔵小杉病院",
    area: "川崎市中原区小杉町1-383",
    region: "川崎市",
    officialUrl: "https://www.nms.ac.jp/kosugi-h/",
    type: "大学病院",
    designation: "災害拠点病院",
  },
  {
    name: "川崎市立井田病院",
    area: "川崎市中原区井田2-27-1",
    region: "川崎市",
    officialUrl: "https://www.city.kawasaki.jp/ida_hospital/index.html",
    type: "公立病院",
    designation: "災害拠点病院",
  },
  {
    name: "北里大学病院",
    area: "相模原市南区北里1-15-1",
    region: "相模原市",
    officialUrl: "https://www.kitasato-u.ac.jp/khp/",
    type: "大学病院",
    designation: "災害拠点病院",
  },
  {
    name: "相模原協同病院",
    area: "相模原市緑区橋本台4-3-1",
    region: "相模原市",
    officialUrl: "https://www.sagamiharahp.com/",
    designation: "災害拠点病院",
  },
  {
    name: "相模原赤十字病院",
    area: "相模原市緑区中野256",
    region: "相模原市",
    officialUrl: "https://www.sagamihara.jrc.or.jp/",
    designation: "災害拠点病院",
  },
  {
    name: "横須賀共済病院",
    area: "横須賀市米が浜通1-16",
    region: "横須賀・三浦",
    officialUrl: "https://ykh.kkr.or.jp/",
    designation: "災害拠点病院",
  },
  {
    name: "横須賀市立市民病院",
    area: "横須賀市長坂1-3-2",
    region: "横須賀・三浦",
    officialUrl: "https://yokosuka-shimin.jp/",
    type: "公立病院",
    designation: "災害拠点病院",
  },
  {
    name: "横須賀市立総合医療センター",
    area: "横須賀市神明町1-8",
    region: "横須賀・三浦",
    officialUrl: "https://ygmc.jp/",
    type: "公立病院",
    designation: "災害拠点病院",
  },
  {
    name: "藤沢市民病院",
    area: "藤沢市藤沢2-6-1",
    region: "湘南エリア",
    officialUrl: "https://fujisawacity-hosp.jp/",
    type: "公立病院",
    designation: "災害拠点病院",
  },
  {
    name: "茅ヶ崎市立病院",
    area: "茅ヶ崎市本村5-15-1",
    region: "湘南エリア",
    officialUrl: "https://hosp.city.chigasaki.kanagawa.jp/",
    type: "公立病院",
    designation: "災害拠点病院",
  },
  {
    name: "東海大学医学部付属病院",
    area: "伊勢原市下糟屋143",
    region: "県央・県西",
    officialUrl: "https://www.fuzoku-hosp.tokai.ac.jp/",
    type: "大学病院",
    designation: "災害拠点病院",
  },
  {
    name: "平塚市民病院",
    area: "平塚市南原1-19-1",
    region: "湘南エリア",
    officialUrl: "https://www.hiratsuka-city-hospital.jp/",
    type: "公立病院",
    designation: "災害拠点病院",
  },
  {
    name: "秦野赤十字病院",
    area: "秦野市立野台1-1",
    region: "県央・県西",
    officialUrl: "https://hadano-jrc.jp/",
    designation: "災害拠点病院",
  },
  {
    name: "厚木市立病院",
    area: "厚木市水引1-16-36",
    region: "県央・県西",
    officialUrl: "https://www.atsugicity-hp.jp/",
    type: "公立病院",
    designation: "災害拠点病院",
  },
  {
    name: "大和市立病院",
    area: "大和市深見西8-3-6",
    region: "県央・県西",
    officialUrl: "https://www.yamatocity-mh.jp/",
    type: "公立病院",
    designation: "災害拠点病院",
  },
  {
    name: "神奈川県立足柄上病院",
    area: "足柄上郡松田町惣領866-1",
    region: "県央・県西",
    officialUrl: "https://ashigarakami.kanagawa-pho.jp/",
    type: "公立病院",
    designation: "災害拠点病院",
  },
  {
    name: "小田原市立総合医療センター",
    area: "小田原市久野46",
    region: "県央・県西",
    officialUrl: "https://www.city.odawara.kanagawa.jp/hospital/",
    type: "公立病院",
    designation: "災害拠点病院",
  },
  {
    name: "汐田総合病院",
    area: "横浜市鶴見区矢向1-6-20",
    region: "横浜市",
    officialUrl: "https://www.ushioda.or.jp/",
    designation: "災害協力病院",
  },
  {
    name: "大口東総合病院",
    area: "横浜市神奈川区入江2-19-1",
    region: "横浜市",
    officialUrl: "https://www.jikei-o.or.jp/oguchi-higashi/",
    designation: "災害協力病院",
  },
  {
    name: "脳神経外科東横浜病院",
    area: "横浜市神奈川区羽沢町888",
    region: "横浜市",
    officialUrl: "https://www.noukyukai.or.jp/",
    type: "専門病院",
    designation: "災害協力病院",
  },
  {
    name: "菊名記念病院",
    area: "横浜市港北区菊名4-4-27",
    region: "横浜市",
    officialUrl: "https://kmh.or.jp/",
    designation: "災害協力病院",
  },
  {
    name: "高田中央病院",
    area: "横浜市港北区高田西2-6-5",
    region: "横浜市",
    officialUrl: "https://sukoyaka-takada.com/",
    designation: "災害協力病院",
  },
  {
    name: "牧野記念病院",
    area: "横浜市緑区鴨居2-21-11",
    region: "横浜市",
    officialUrl: "https://makino-hp.jp/",
    designation: "災害協力病院",
  },
  {
    name: "横浜総合病院",
    area: "横浜市青葉区鉄町2201-5",
    region: "横浜市",
    officialUrl: "https://yokoso.or.jp/",
    designation: "災害協力病院",
  },
  {
    name: "聖隷横浜病院",
    area: "横浜市保土ケ谷区岩井町215",
    region: "横浜市",
    officialUrl: "https://www.seirei.or.jp/yokohama/",
    designation: "災害協力病院",
  },
  {
    name: "上白根病院",
    area: "横浜市旭区上白根2-65-1",
    region: "横浜市",
    officialUrl: "https://www.med-keiseikai.or.jp/kami/",
    designation: "災害協力病院",
  },
  {
    name: "横浜鶴ヶ峰病院",
    area: "横浜市旭区川島町1764",
    region: "横浜市",
    officialUrl: "https://tsurugaminehospital.com/",
    designation: "災害協力病院",
  },
  {
    name: "西横浜総合病院",
    area: "横浜市戸塚区汲沢町56",
    region: "横浜市",
    officialUrl: "https://www.nishiyokohama.or.jp/",
    designation: "災害協力病院",
  },
  {
    name: "戸塚共立第1病院",
    area: "横浜市戸塚区戸塚町116",
    region: "横浜市",
    officialUrl: "https://www.tk1-hospital.com/",
    designation: "災害協力病院",
  },
  {
    name: "平成横浜病院",
    area: "横浜市戸塚区戸塚町550",
    region: "横浜市",
    officialUrl: "https://yokohamahp.jp/",
    designation: "災害協力病院",
  },
  {
    name: "東戸塚記念病院",
    area: "横浜市戸塚区品濃町548-7",
    region: "横浜市",
    officialUrl: "https://www.higashi-totsuka.com/",
    designation: "災害協力病院",
  },
];

const pinCenters = {
  横浜市: { top: 43, left: 60 },
  川崎市: { top: 22, left: 81 },
  相模原市: { top: 23, left: 24 },
  "横須賀・三浦": { top: 79, left: 69 },
  湘南エリア: { top: 70, left: 43 },
  "県央・県西": { top: 54, left: 24 },
};

const makeMapUrl = (name) =>
  `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(name)}`;

export const hospitals = verifiedHospitals.map((hospital, index) => {
  const id = index + 1;
  const center = pinCenters[hospital.region];
  const xOffset = ((id * 17) % 13) - 6;
  const yOffset = ((id * 11) % 11) - 5;

  return {
    id,
    ...hospital,
    image: hospital.image ?? null,
    imageNote: hospital.imageNote ?? "外観画像は公式サイト確認後に追加予定",
    type: hospital.type ?? "総合病院",
    tags: [hospital.designation, "公式情報確認済み"],
    role: "看護師採用情報",
    salary: "公式サイトで確認",
    shift: "採用条件は公式サイトへ",
    holidays: "2026年7月確認",
    station: hospital.access ?? "交通アクセスは公式サイトで確認",
    recruitUrl: hospital.recruitUrl ?? hospital.officialUrl,
    mapsUrl: makeMapUrl(hospital.name),
    pin: {
      top: `${center.top + yOffset * 0.9}%`,
      left: `${center.left + xOffset * 0.8}%`,
    },
  };
});

export const filters = [
  {
    key: "area",
    label: "勤務地",
    options: [
      "神奈川県",
      "横浜市",
      "川崎市",
      "相模原市",
      "横須賀・三浦",
      "湘南エリア",
      "県央・県西",
    ],
  },
  {
    key: "facility",
    label: "施設形態",
    options: ["すべて", "総合病院", "公立病院", "大学病院", "専門病院"],
  },
  {
    key: "workStyle",
    label: "働き方",
    options: ["こだわらない", "常勤", "日勤のみ", "夜勤あり", "夜勤専従", "2交替", "3交替"],
  },
  {
    key: "preference",
    label: "こだわり条件",
    options: [
      "指定なし",
      "月給30万円以上",
      "年間休日120日以上",
      "土日祝休み",
      "託児所あり",
      "寮あり",
      "駅徒歩10分以内",
      "未経験可",
      "ブランク可",
    ],
  },
];
